config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'
  resources :users
  resources :posts
  resources :comments
  resources :favourites
  resources :profiles
  resources :roles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :content, presence: true, length: { maximum: 140 }, format: /[a-z A-Z 0-9]*/
	validates :user_id, presence: true
	validates :post_id, presence: true
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :user_id, presence: true
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :favourites

	validates :content, presence: true
	validates :title, presence: true, length: { maximum: 140 }, format: /[a-z A-Z 0-9]*/
	validates :user_id, presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true
	validates :title, presence: true, length: { maximum: 140 }, format: /[a-z A-Z 0-9]*/
	validates :hits, numericality: { only_integer: true }

	after_create :set_hits_to_zero
    after_find :add_hit

    scope :popular, -> { where("hits>100") }

    protected 
    
    def set_hits_to_zero 
        self.hits=0 
    end 

    def add_hit
    	self.hits += 1
    end
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users

	validates :role_name, presence: true, format: /[a-z]*/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :trackable, :validatable

    has_many :posts
	has_and_belongs_to_many :roles
	has_one :profile
	has_many :comments
	has_many :favourites

	validates :login, presence: true, length: { maximum: 30 }, format: /[a-z A-Z 0-9]*/, uniqueness: true, 
				exclusion: { in: %w(admin superuser) }
	validates :encrypted_password, presence: true, length: { maximum: 80 }, format: /[a-z A-Z 0-9]*/
	validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}, uniqueness: true
	validates :age, inclusion: {in: 1..100}, numericality: true

	before_validation :ensure_login_has_a_value

	scope :old, -> { where("age>60") }

 
  	protected
    
    def ensure_login_has_a_value
      if login.nil?
        self.login = email unless email.blank?
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters

  devise_parameter_sanitizer.for(:sign_up) << :age

end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.all
	end

	def show
		@comment = Comment.find(params[:id])
	end

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		if @comment.save
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update(comment_params)
			redirect_to posts_path
		else
			render 'edit'
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to comments_path
	end

	private

	def comment_params
		params.require(:comment).permit(:user_id, :post_id, :content)
	end


end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
	def index
		@favourites = Favourite.all
	end

	def new
		@favourite = Favourite.new
	end

	def create
		@favourite = Favourite.new(favourite_params)
		if @favourite.save
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def destroy
		@favourite = Favourite.find(params[:id])
		@favourite.destroy
		redirect_to posts_path
	end

	private

	def favourite_params
		params.require(:favourite).permit(:user_id, :post_id)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to posts_path
		else 
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params 
        params.require(:post).permit(:content, :title, :user_id) 
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index
		@profiles = Profile.all
	end

	def show
		@profile = Profile.find(params[:id])
	end

	def new
		@profile = Profile.new
	end

	def create
		@profile = Profile.new(profile_params)
		if @profile.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profile_params)
			redirect_to profiles_path
		else
			render 'edit'
		end
	end

	def destroy
		@profile = Profile.find(params[:id])
		@profile.destroy
		redirect_to profiles_path
	end

	private

	def profile_params
		params.require(:profile).permit(:title, :hits, :user_id)
	end


end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
	def index
		@roles = Role.all
	end

	def new
		@role = Role.new
	end

	def create
		@role = Role.new(role_params)
		if @role.save
			redirect_to roles_path
		else
			render 'new'
		end
	end

	def edit
		@role = Role.find(params[:id])
	end

	def update
		@role = Role.find(params[:id])
		if @role.update(role_params)
			redirect_to roles_path
		else 
			render 'edit'
		end
	end

	def destroy
		@role = Role.find(params[:id])
		@role.destroy
		redirect_to roles_path
	end

	private

	def role_params 
        params.require(:role).permit(:role_name) 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.haml
%h1 Edit the comment
= form_for(@comment) do |f|
  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit "Edit!"

app/views/comments/index.html.haml
%h1 All comments
%ul
  - @comments.each do |comment|
    %li
      = comment.content + " " + comment.post_id.to_s + " " + comment.user_id.to_s
      = link_to "Show", comment
      = link_to "Edit this comment", edit_comment_path(comment)
      = link_to "Delete this comment", comment, method: :delete, data: { confirm: 'Are you sure?' }
= link_to "Back to posts", posts_path

app/views/comments/new.html.haml
%h1 Comment the post
- if @comment.errors.any?
  #error_explanation
    %h2
      = pluralize(@comment.errors.count, "error")
      prohibited this comment from being saved:
    %ul
      - @comment.errors.full_messages.each do |message|
        %li= message
= form_for(@comment) do |f|
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :post_id
    %br/
    = f.number_field :post_id
  .actions
    = f.submit "Add!"

app/views/comments/show.html.haml
%h3
  = @comment.user_id
  wrote:
%br/
%h4
  = @comment.content
%br/
%h5
  Under post: #{@comment.post_id}
%br/
%br/
= link_to "Back", comments_path

app/views/favourites/index.html.haml
%h1 Look all the favourites!
%ul
  - @favourites.each do |favourite|
    %li
      = favourite.user_id
      likes #{favourite.post_id}
      \#{link_to "Delete this favourite", favourite, method: :delete, data: { confirm: 'Are you sure?' }}
= link_to "Back to posts", posts_path

app/views/favourites/new.html.haml
%h1 Like this
= form_for(@favourite) do |f|
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :post_id
    %br/
    = f.number_field :post_id
  .actions
    = f.submit "Like!"

app/views/layouts/_navbar.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} 
        = link_to image_tag( 'firm.jpg')
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Register', new_user_registration_path
        %li
          - if user_signed_in?
            = link_to 'Sign out', destroy_user_session_path, method: :delete, data: { confirm: 'We will miss you :(' } 
          - else
            = link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
%html
  %head
    %title Blogtest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-fixed-top{ id: current_user ? 'active' :nil }
      =render 'layouts/navbar'
    %div.container
      = yield 

app/views/posts/edit.html.haml
%h1 Editpost
= form_for(@post) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit "Add!"

app/views/posts/index.html.haml
%h1 Posts dashboard
%br/
= link_to "Create new post", new_post_path
%br/
%ul
  - @posts.each do |post|
    %li
      = post.title + " " + post.user_id.to_s + " " + post.created_at.to_s
      = link_to "Show content", post
      = link_to "Edit this post", edit_post_path(post)
      = link_to "Delete this post", post, method: :delete, data: { confirm: 'Are you sure?' }
= link_to "Show all favourites", favourites_path
%br/
= link_to "Show all comments", comments_path

app/views/posts/new.html.haml
%h1 Create new post
= form_for(@post) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .actions
    = f.submit "Add!"

app/views/posts/show.html.haml
%h1
  = @post.title
%br/
%h4
  = @post.content
%br/
%h6
  = @post.user_id
%br/
= link_to "Comment this post", new_comment_path
%br/
= link_to "Favourite this post", new_favourite_path
%br/
= link_to "Back", posts_path

app/views/profiles/edit.html.haml
%h1 Edit profile
= form_for(@profile) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :hits
    = f.number_field :hits
  .actions
    = f.submit "Save!"

app/views/profiles/index.html.haml
%h1 All profiles
%ul
  - @profiles.each do |profile|
    %li
      = profile.user_id
      = link_to "Show", profile
      = link_to "Edit this profile", edit_profile_path(profile)
      = link_to "Delete this profile", profile, method: :delete, data: { confirm: 'Are you sure?' }
= link_to "Back to users", users_path

app/views/profiles/new.html.haml
%h1 New profile
= form_for(@profile) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :hits
    = f.number_field :hits
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .actions
    = f.submit "Save!"

app/views/profiles/show.html.haml
%h1
  = @profile.user_id
  's profile
%h2
  = @profile.title
%br/
%h5
  Hits: #{@profile.hits.to_s}
%h6
  Created at #{@profile.created_at.to_s}
= link_to "Back", profiles_path

app/views/roles/edit.html.haml
%h1 Edit role
= form_for(@role) do |f|
  .field
    = f.label :role_name
    = f.text_field :role_name
  .actions
    = f.submit "Save!"

app/views/roles/index.html.haml
%h1 All roles
%br/
= link_to "Create new role", new_role_path
%br/
%ul
  - @roles.each do |role|
    %li
      = role.role_name
      = link_to "Edit this role", edit_role_path(role)
      = link_to "Delete this role", role, method: :delete, data: { confirm: 'Are you sure?' }
= link_to "Back to users", users_path

app/views/roles/new.html.haml
%h1 New role
= form_for(@role) do |f|
  .field
    = f.label :role_name
    = f.text_field :role_name
  .actions
    = f.submit "Create!"

app/views/users/show.html.haml
%h1
  = @user.login
  's profile
%h2
  = @user.email
%br/
%h4
  = "Age: " + @user.age.to_s
  %br/
  = "Last signed in at: " + @user.last_sign_in_at.to_s
%h6
= link_to "Back", posts_path